django_level_five/basicapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'basicapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.user_reg, name='user_reg'),
    url(r'^login/$', views.user_login, name='user_login'),
]

django_level_five/django_level_five/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basicapp/', include('basicapp.urls')),
    url(r'^$', views.index, name='home_index'),
]

django_level_five/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    # Create relationship between user and User(user dont inherit from  User)
    user = models.OneToOneField(User)

    # Add new fields/attributes

    portfolio_site = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

django_level_five/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm():
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'picture')

django_level_five/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm

# Create your views here.


def index(request):
    return render(request, 'basicapp/index.html')


def user_login(request):
    return render(request, 'basicapp/login.html')


def user_reg(request):

    registered = False

    if request.method == 'POST':

django_level_five/django_level_five/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

django_level_five/basicapp/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
</head>
<body>

        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'basicapp:index' %}">Home</a>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'basicapp:user_reg' %}">Register</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'basicapp:user_login' %}">Login</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>

</body>
</html>

django_level_five/basicapp/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

django_level_five/basicapp/templates/basicapp/login.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

django_level_five/basicapp/templates/basicapp/register.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <div class="container">
        <form action="" method="post" role="form">
            <legend>Form Title</legend>

            <div class="form-group">
                <label for=""></label>
                <input type="text" class="form-control" name="" id="" placeholder="Input...">
            </div>

            

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

django_level_five/templates/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h1>Index App</h1>
</body>
</html>